### ISSUE TITLE
Fails to parse any string with a comparator [version 0.3.0]

### ISSUE THREAD

**Issue by ohaswin** [figsoda/pep-508#1]
Here's a sample code I tried running:
```rust
use pep_508;

fn main() {
    let s = pep_508::parse("vyper <= '1.0.1'");
    println!("{:?}", s)
}
```

Here's the error I get:
```bash
Err([found end of input at 9..10])
```

Parser works perfectly fine on just the dependency names but anything with a comparator throws me that error. I have tried various ways to make the string but still no use.

**Comment by figsoda** [comment]
I don't think that's valid PEP 508 syntax, what you are looking for is `vyper <= 1.0.1` (without the single quotes)

**Comment by ohaswin** [comment]
oh yeah, that's right, my bad. thanks for the hint
